function UniversityofAlabamaenrollments = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNIVERSITYOFALABAMAENROLLMENTS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  UNIVERSITYOFALABAMAENROLLMENTS = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  UniversityofAlabamaenrollments = importfile("C:\Users\xalan\MATLAB\Projects\pso_fts\University of Alabama enrollments.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Dec-2019 17:14:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Fall", "MaleNo", "Male", "FemaleNo", "Female", "Total"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["MaleNo", "FemaleNo", "Total"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["MaleNo", "FemaleNo", "Total"], "ThousandsSeparator", ",");

% Import the data
UniversityofAlabamaenrollments = readtable(filename, opts);

end